spring:
  profiles:
    active: local

  logging.level.org.springframework.batch: DEBUG
  
---

spring:
  profiles:
  - local
         
  datasource: 
     url: jdbc:mysql://127.0.0.1:3306/projectadmin?characterEncoding=UTF-8&serverTimezone=UTC
     username: root 
     password: 1234 
     driver-Class-Name: com.mysql.cj.jdbc.Driver
  jpa:
     database : mysql
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     generate-ddl: true
     show-sql: true
     open-in-view: false
           
      
  
  servlet:
      multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB        
        enabled: true      
  
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false 
      
server:
 port: 9000
 tomcat:
    uri-encoding: UTF-8
    
 servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
       
    session: 
      timeout: 7200
 error:
      whitelabel:
        enabled: false

logging:
  config: classpath:logback-spring.xml  

mybatis:
  type-aliases-package: com.project.example.domain
  mapper-locations: mapper/**/*.xml
 